function varplot(stats, hFig)

figure(hFig); 

% plot mean: line length depending on histogram max 
line([stats(1) stats(1)], ...
     [stats(4)*0.3 stats(4)*0.7], ...
     'color', 'red', 'linewidth', 2)
 
 % plot standard deviation ...
 line([(stats(1)-stats(2)/2) (stats(1)+stats(2)/2)], ...
     [stats(4)*0.5 stats(4)*0.5], ...
     'color', 'green', 'linewidth', 2)
% ... with bordering left and right 'wings'
   line([(stats(1)-stats(2)/2) (stats(1)-stats(2)/2)], ...
     [stats(4)*0.45 stats(4)*0.55], ...
     'color', 'green', 'linewidth', 2)
 
 line([(stats(1)+stats(2)/2) (stats(1)+stats(2)/2)], ...
     [stats(4)*0.45 stats(4)*0.55], ...
     'color', 'green', 'linewidth', 2)

end % function varplot